package exceptionHandeling.finally_block;

public class Exception_4 {
}

/*
     Rule: For each try block there can be zero or more catch blocks,
     but only one finally block.
     Note: The finally_block will not be executed if the program exits
     (either by calling System.exit() or by causing a fatal error that causes the
      process to abort).
*/
